# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# TODO: add milestone function

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReadingScreen(object):
    def setupUi(self, MainWindow, widget, text):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1024)
        MainWindow.setStyleSheet("background-color: rgb(252, 255, 237);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 80, 1211, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("border: 10px solid #324143;\n"
"background: #FFF;\n"
"width: 2023;\n"
"height: 1223;\n"
"padding: -10 px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.text = QtWidgets.QTextBrowser(self.frame)
        self.text.setStyleSheet("border: 0px;")
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 0, 0, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(40, 810, 1213, 153))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setStyleSheet("height: 100px;")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.leftArrow = QtWidgets.QPushButton(self.horizontalWidget)
        self.leftArrow.setGeometry(QtCore.QRect(2, 15, 95, 123))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftArrow.sizePolicy().hasHeightForWidth())
        self.leftArrow.setSizePolicy(sizePolicy)
        self.leftArrow.setStyleSheet("width: 86.017px;\n"
"height: 113.996px;\n"
"transform: rotate(-90.227deg);\n"
"\n"
"")
        self.leftArrow.setText("")
        self.leftArrow.setFlat(True)
        self.leftArrow.setAutoFillBackground(True)
        self.leftArrow.setStyleSheet("background: #FCFFED;")
        arrowIcon = QtGui.QIcon()
        arrowIcon.addPixmap(QtGui.QPixmap("UI/icons/leftArrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leftArrow.setIcon(arrowIcon)
        self.leftArrow.setIconSize(QtCore.QSize(86, 114))
        self.leftArrow.setObjectName("leftArrow")
        
        self.rightArrow = QtWidgets.QPushButton(self.horizontalWidget)
        self.rightArrow.setGeometry(QtCore.QRect(1116, 15, 95, 123))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightArrow.sizePolicy().hasHeightForWidth())
        self.rightArrow.setSizePolicy(sizePolicy)
        self.rightArrow.setText("")
        self.rightArrow.setFlat(True)
        self.rightArrow.setAutoFillBackground(True)
        self.rightArrow.setStyleSheet("background: #FCFFED;")
        arrowIcon = QtGui.QIcon()
        arrowIcon.addPixmap(QtGui.QPixmap("UI/icons/rightArrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rightArrow.setIcon(arrowIcon)
        self.rightArrow.setIconSize(QtCore.QSize(86, 114))
        self.rightArrow.setObjectName("rightArrow")

        self.progressFullBar = QtWidgets.QFrame(self.horizontalWidget)
        self.progressFullBar.setGeometry(QtCore.QRect(150, 60, 921, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressFullBar.sizePolicy().hasHeightForWidth())
        self.progressFullBar.setSizePolicy(sizePolicy)
        self.progressFullBar.setStyleSheet("width: 700px;\n"
"height: 18px;\n"
"background: #C8E3E8;")
        self.progressFullBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.progressFullBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.progressFullBar.setObjectName("progressFullBar")
        self.progressFullBar_2 = QtWidgets.QFrame(self.progressFullBar)
        self.progressFullBar_2.setGeometry(QtCore.QRect(0, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressFullBar_2.sizePolicy().hasHeightForWidth())
        self.progressFullBar_2.setSizePolicy(sizePolicy)
        self.progressFullBar_2.setStyleSheet("width: 700px;\n"
"height: 18px;\n"
"background: #4E8696;")
        self.progressFullBar_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.progressFullBar_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.progressFullBar_2.setObjectName("progressFullBar_2")

        self.Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(1270, 140, 86, 114))
        self.Settings.setText("")
        self.Settings.setFlat(True)
        self.Settings.setAutoFillBackground(True)
        self.Settings.setStyleSheet("background: #FCFFED;")
        gearIcon = QtGui.QIcon()
        gearIcon.addPixmap(QtGui.QPixmap("UI/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Settings.setIcon(gearIcon)
        self.Settings.setIconSize(QtCore.QSize(86, 114))
        self.Settings.setObjectName("Settings")

        self.configDoc = QtWidgets.QPushButton(self.centralwidget)
        self.configDoc.setGeometry(QtCore.QRect(1270, 270, 86, 114))
        self.configDoc.setText("")
        self.configDoc.setFlat(True)
        self.configDoc.setAutoFillBackground(True)
        self.configDoc.setStyleSheet("background: #FCFFED;")
        configIcon = QtGui.QIcon()
        configIcon.addPixmap(QtGui.QPixmap("UI/icons/doc.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.configDoc.setIcon(configIcon)
        self.configDoc.setIconSize(QtCore.QSize(86, 114))
        self.configDoc.setObjectName("configDoc")

        self.textToSpeech = QtWidgets.QPushButton(self.centralwidget)
        self.textToSpeech.setGeometry(QtCore.QRect(1270, 400, 86, 114))
        self.textToSpeech.setText("")
        self.textToSpeech.setFlat(True)
        self.textToSpeech.setAutoFillBackground(True)
        self.textToSpeech.setStyleSheet("background: #FCFFED;")
        speechIcon = QtGui.QIcon()
        speechIcon.addPixmap(QtGui.QPixmap("UI/icons/audio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.textToSpeech.setIcon(speechIcon)
        self.textToSpeech.setIconSize(QtCore.QSize(86, 114))
        self.textToSpeech.setStyleSheet("width: 86.017px;\n"
"height: 113.996px;\n"
"")
        self.textToSpeech.setObjectName("textToSpeech")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADHD Reader"))
        # self.Settings.setText(_translate("MainWindow", "..."))
        # self.configDoc.setText(_translate("MainWindow", "..."))
        # self.textToSpeech.setText(_translate("MainWindow", "..."))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_Partition()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
