# Form implementation generated from reading ui file 'designerUIFiles/milestones/Reading-Comp-Continue-Layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(713, 658)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(parent=self)
        self.title.setStyleSheet("QLabel {\n"
"    color: #324143;\n"
"    font-family: Niramit;\n"
"    font-size: 65px;\n"
"    font-style: normal;\n"
"    font-weight: 600;\n"
"    line-height: normal;\n"
"}")
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.checkImage = QtWidgets.QLabel(parent=self)
        self.checkImage.setText("")
        self.checkImage.setPixmap(QtGui.QPixmap("UI/milestoneUI/check.png"))
        self.checkImage.setObjectName("checkImage")
        self.verticalLayout.addWidget(self.checkImage, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.continueLabel = QtWidgets.QLabel(parent=self)
        self.continueLabel.setStyleSheet("QLabel {\n"
"    color: #324143;\n"
"    text-align: center;\n"
"    font-family: Niramit;\n"
"    font-size: 45px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}")
        self.continueLabel.setObjectName("continueLabel")
        self.verticalLayout.addWidget(self.continueLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Nice work!"))
        self.continueLabel.setText(_translate("Form", "Let\'s continue."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = Ui_Form()
    Form.show()
    sys.exit(app.exec())
