# Timer implementation generated from reading ui file 'designerUIFiles/milestones/takeABreakPartTwo.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(838, 802)
        Timer.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Timer)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLayout = QtWidgets.QFrame(parent=Timer)
        self.titleLayout.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleLayout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titleLayout.setObjectName("titleLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.titleLayout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.title = QtWidgets.QLabel(parent=self.titleLayout)
        self.title.setStyleSheet("color: #324143;\n"
"font-family: Niramit;\n"
"font-size: 55px;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"line-height: normal;")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_3.addWidget(self.title)
        self.subtitle = QtWidgets.QLabel(parent=self.titleLayout)
        self.subtitle.setStyleSheet("color: #324143;\n"
"font-family: Roboto;\n"
"font-size: 30px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.verticalLayout_3.addWidget(self.subtitle)
        self.verticalLayout.addWidget(self.titleLayout)
        self.timerWidgetLayout = QtWidgets.QHBoxLayout()
        self.timerWidgetLayout.setContentsMargins(20, -1, 20, -1)
        self.timerWidgetLayout.setObjectName("timerWidgetLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timerWidgetLayout.addItem(spacerItem1)
        self.timer = QtWidgets.QWidget(parent=Timer)
        self.timer.setMinimumSize(QtCore.QSize(400, 400))
        self.timer.setStyleSheet("")
        self.timer.setObjectName("timer")
        self.time = QtWidgets.QLabel(parent=self.timer)
        self.time.setGeometry(QtCore.QRect(100, 150, 200, 100))
        self.time.setStyleSheet("color: #000;\n"
"font-family: Roboto;\n"
"font-size: 75px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.time.setObjectName("time")
        self.sText = QtWidgets.QLabel(parent=self.timer)
        self.sText.setGeometry(QtCore.QRect(300, 190, 21, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(37)
        font.setKerning(True)
        self.sText.setFont(font)
        self.sText.setStyleSheet("color: #324143;\n"
"font-family: Roboto;\n"
"font-size: 30px;\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"line-height: normal;")
        self.sText.setObjectName("sText")
        self.circularProgress = QtWidgets.QFrame(parent=self.timer)
        self.circularProgress.setGeometry(QtCore.QRect(50, 50, 300, 300))
        self.circularProgress.setStyleSheet("QFrame {\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(255, 170, 255, 0), stop:.75 rgba(78, 134, 150, 255));\n"
"}")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.progressForeground = QtWidgets.QFrame(parent=self.circularProgress)
        self.progressForeground.setGeometry(QtCore.QRect(10, 10, 280, 280))
        self.progressForeground.setStyleSheet("QFrame {\n"
"    border-radius: 140px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.progressForeground.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.progressForeground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.progressForeground.setObjectName("progressForeground")
        self.progressBackground = QtWidgets.QFrame(parent=self.timer)
        self.progressBackground.setGeometry(QtCore.QRect(10, 10, 375, 375))
        self.progressBackground.setStyleSheet("QFrame {\n"
"    border-radius: 187px;\n"
"    background-color: rgb(200, 227, 232);\n"
"}")
        self.progressBackground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.progressBackground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.progressBackground.setObjectName("progressBackground")
        self.progressBackground.raise_()
        self.circularProgress.raise_()
        self.time.raise_()
        self.sText.raise_()
        self.timerWidgetLayout.addWidget(self.timer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timerWidgetLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.timerWidgetLayout)
        self.pauseRestartButtonsLayout = QtWidgets.QHBoxLayout()
        self.pauseRestartButtonsLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.pauseRestartButtonsLayout.setContentsMargins(-1, 0, -1, -1)
        self.pauseRestartButtonsLayout.setSpacing(60)
        self.pauseRestartButtonsLayout.setObjectName("pauseRestartButtonsLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pauseRestartButtonsLayout.addItem(spacerItem3)
        self.pauseButton = QtWidgets.QPushButton(parent=Timer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(75, 75))
        self.pauseButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pauseButton.setBaseSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.pauseButton.setFont(font)
        self.pauseButton.setStyleSheet("QPushButton {\n"
"    border-color: rgb(255, 255, 255);\n"
"    color: rgb(78, 134, 150);\n"
"    background-color: rgb(200, 227, 232);\n"
"    border: none;    \n"
"    border-radius: 35px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(161, 197, 200);\n"
"}")
        self.pauseButton.setObjectName("pauseButton")
        self.pauseRestartButtonsLayout.addWidget(self.pauseButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.restartButton = QtWidgets.QPushButton(parent=Timer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartButton.sizePolicy().hasHeightForWidth())
        self.restartButton.setSizePolicy(sizePolicy)
        self.restartButton.setMinimumSize(QtCore.QSize(75, 75))
        self.restartButton.setMaximumSize(QtCore.QSize(75, 75))
        self.restartButton.setStyleSheet("QPushButton {\n"
"    border-color: rgb(255, 255, 255);\n"
"    color: rgb(78, 134, 150);\n"
"    background-color: rgb(200, 227, 232);\n"
"    border: none;    \n"
"    border-radius: 35px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(161, 197, 200);\n"
"}")
        self.restartButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designerUIFiles/milestones/output-onlinepngtools.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restartButton.setIcon(icon)
        self.restartButton.setIconSize(QtCore.QSize(55, 55))
        self.restartButton.setObjectName("restartButton")
        self.pauseRestartButtonsLayout.addWidget(self.restartButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pauseRestartButtonsLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.pauseRestartButtonsLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Timer"))
        self.title.setText(_translate("Timer", "Take a break."))
        self.subtitle.setText(_translate("Timer", "Time Left:"))
        self.time.setText(_translate("Timer", "00:00"))
        self.sText.setText(_translate("Timer", "s"))
        self.pauseButton.setText(_translate("Timer", "ll"))